services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-quotes}
      POSTGRES_USER: ${POSTGRES_USER:-quotes}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-quotes}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-quotes} -d ${POSTGRES_DB:-quotes}" ]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    env_file: ./.env
    environment:
      POSTGRES_HOST: db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ../src/quotes:/app/quotes
      - ../src/quotes_project:/app/quotes_project
      - ../src/manage.py:/app/manage.py

volumes:
  postgres_data:
